# Generated by Django 6.0.3 on 2026-07-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='name',
            field=models.CharField(blank=True, help_text='Shown in the whoami card, e.g. "Your Name".', max_length=255, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='open_to',
            field=models.CharField(blank=True, help_text='e.g. "cool things".', max_length=255, verbose_name='Open to'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='role',
            field=models.CharField(blank=True, help_text='e.g. "software dev".', max_length=255, verbose_name='Role'),
        ),
    ]
