# Generated by Django 6.0.3 on 2026-07-08 07:49

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_me',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='About me'),
        ),
    ]
